baseURL = "https://netZoo.github.io"
languageCode = "en-us"
title = "The network zoo"
theme = "hugo-theme-learn"
googleAnalytics =  "G-TRXH486JVZ"
publishDir = "docs"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

# For search functionality
[outputs]
home = ["HTML","RSS","JSON"]

[[menu.shortcuts]] 
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "da"
url = "https://github.com/netZoo"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-book-reader'></i> Netbooks"
identifier = "dde"
url = "https://netbooks.networkmedicine.org/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-cloud'></i> Travis-ci"
identifier = "db"
url = "https://travis-ci.org/github/netZoo/netZooC"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-cloud'></i> ZooKeeper"
identifier = "dc"
url = "https://github.com/netZoo/netZooR/actions"
weight = 13

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Codecov"
identifier = "dd"
url = "https://codecov.io/gh/netZoo"
weight = 14

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope-square'></i> Contact"
identifier = "de"
url = "mailto:benguebila@hsph.harvard.edu"
weight = 15

[params]
	description= "Network biology packages"
	themeVariant = "red"
