baseURL = "https://www.netZoo.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
relativeURLs = true
preserveTaxonomyNames = true
enableemoji = true

pygmentsCodefences = true
pygmentsStyle = "friendly"

[params]
    mdlversion = "1.3.0"
    mdltheme = "teal-indigo"

[taxonomies]
    tag = "tags"
