baseURL = "https://netZoo.github.io"
languageCode = "en-us"
title = "The network zoo"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = ["HTML","RSS","JSON"]

[[menu.shortcuts]] 
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "da"
url = "https://github.com/netZoo"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-cloud'></i> Travis-ci"
identifier = "db"
url = "https://travis-ci.com/netZoo"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-cloud'></i> ZooKeeper"
identifier = "dc"
url = "http://zookeeper.networkmedicine.org/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Codecov"
identifier = "dd"
url = "https://codecov.io/gh/netZoo"
weight = 13

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-envelope-square'></i> Contact"
identifier = "de"
url = "mailto:twang@hsph.harvard.edu"
weight = 14

[params]
	description= "Network biology packages"
	themeVariant = "purple"
